config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

  root "welcome#home"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :posts, only: [:index, :new, :show]
  end

  resources :posts do
    member do
      get 'like', to: 'posts#upvote'
      get 'dislike', to: 'posts#downvote'
    end
    resources :comments
  end

  get 'search' => 'search#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord

  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
  
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_hash_tags, on: :create

  acts_as_votable
  belongs_to :user

  has_many :comments
  has_many :users, through: :comments, dependent: :destroy

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  validates :title, presence: true, length: { maximum: 25 }
  validates :description, presence: true

  has_attached_file :image, styles: { medium: "800x600#", small: "350x250>" }
  # validates :image, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.recent
    order("posts.updated_at DESC")
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end

  def next
    posts = post_ids_by_updated
    post_index = posts.find_index(id)
    next_post = post_index + 1

    if next_post < posts.length
      posts[next_post]
    else
      id
    end
  end

  def prev
    posts = post_ids_by_updated
    post_index = posts.find_index(id)
    prev_post = post_index - 1

    if prev_post > 0
      posts[prev_post]
    else
      id
    end
  end

  private

  def post_ids_by_updated
    @post_ids ||= Post.order(updated_at: :desc).pluck(:id)
  end

end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord

  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy

  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :username, presence: true, length: { maximum: 30 }
  validates :bio, length: { maximum: 1000 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :username, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :username, :password, :current_password)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      render json: @comment, status: 201
    else
      render 'post/show'
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!

  def index
    if params[:author_id]
      @posts = Author.find(params[:author_id]).posts.paginate(:page => params[:page], per_page: 9)
    else
      @posts = Post.recent.paginate(:page => params[:page], per_page: 9)
    end
    respond_to do |format|
      format.html
      format.json {render json: @posts}
    end
  end

  def show
    @comments = Comment.where(post_id: @post)

    respond_to do |format|
      format.html
      format.json {render json: @post}
    end
  end

  def new
     @post = Post.new(user_id: params[:user_id])
  end

  def create
    # user_id column will be generated when a post is created
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(@post.user, @post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to user_post_path(@post.user, @post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @post.downvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:title, :link, :description, :image, :user_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name: query})
    else
      @posts = Post.where("title like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
    @posts = @user.posts.order(created_at: :desc)
    @user = User.find(params[:id])
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user, status: 200}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :bio, :image, :password, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def paginate_posts
    paginate(:page => params[:page], per_page: 9)
  end

  def edit_post
    if @post.user == current_user
      link_to "Edit", edit_post_path(@post), class: "data"
    end
  end

  def delete_post
    if @post.user == current_user
      link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "data"
    end
  end

  def posted_at
    time_ago_in_words(@post.created_at)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def profile_pic
    if @user.avatar.exists?
      image_tag @user.avatar.url, class: "avatar"
    else
      image_tag("avatar_png_71508", class: "avatar")
    end
  end

  def edit_profile
    if @user == current_user
      link_to "Edit Profile", edit_user_path(@user), class: "edit-profile button"
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

    <%= f.label "Reply to thread", class: "comment_label" %>
    <%= f.text_area :content, class: "textarea", required: true %>

    <%= f.submit class: "button", id: "subBtn", data: { disable_with: false } %>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="container footer">
  <nav class="navbar d-flex">
    <p> © 2019 VISIONZ </p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="wrapper clearfix">
  <div class="logo">
    <%= link_to 'Visionz', root_path %>
  </div>
    <nav>
      <div class="search">
        <%= form_with id: 'js-search', url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
        <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: 'Find a Vision' %>
        <% end %>
      </div>

      <% if user_signed_in? %>
        <%= link_to current_user.name, user_path(current_user) %>
        <%= link_to "Get Inspired", root_path, class: "button" %>
        <%= link_to "Add New Inspiration", new_user_post_path(current_user), class: "button" %>
        <a href="<%= destroy_user_session_path %> "data-method="delete">Sign Out
          <i class="fa fa-user"></i>
        </a>
      <% else %>
        <a href="<%= new_user_session_path%>">Sign In
          <i class="fa fa-sign-in"></i>
        </a>
        <%= link_to "Sign Up", new_user_registration_path, class: "button" %>
      <% end %>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Visionz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Bellefair|David+Libre:400,700|Goudy+Bookletter+1911|Katibeh|Roboto:100,300,400,500,700|Sumana|Suranna|Titillium+Web:200,300,400,700&display=swap" rel="stylesheet">

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<!-- Form for creating a new Vision -->

<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title %>
    </div>

    <%= f.hidden_field :user_id %>

    <div class="field">
      <%= f.label :link, class: "form-label" %>
      <%= f.text_field :link %>
    </div>

    <div class="field">
      <%= f.label :description, class: "form-label" %><br>
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :image, class: "form-label" %><br>
      <%= f.file_field :image, class: "image-upload" %>
    </div><br>

    <div class="">
      <%= f.submit "Create a Vision", class: "btn btn-primary " %>
    </div

<% end %>


<br>
<!-- container for new vision -->
<div class="container">
  <div id="postResult">
    <h2 id="postTitle"></h2>
    <p id="postBody"></p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="form_heading">Edit <%= @post.title %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
<div id="intro">
  <p>Hello <%= current_user.name %></p>
  <span>Share your inspirations and see what's inspiring others!</span><br>
  <span>There are currently <%= @posts.count %> inspiring visions being shared!</span>
</div>
<% end %>


<!-- <button class="button" id="load-posts" type="button" name="button">Load Visionz</button><br />
<div id="js-post"><br>

</div> -->


<div class="container">
  <div id="posts">
    <span id="pagination">
      <%= will_paginate @posts %>
    </span>
    <% @posts.each do |post| %>
      <div class="post">
        <div class="post_image">
          <%= link_to (image_tag post.image.url(:small)), user_post_path(post.user, post) %>
        </div>
        <div class="post_content">
          <h2 class="title">
            <%= link_to post.title, user_post_path(post.user, post) %>
          </h2>
          <div class="data clearfix">
            <p class="username">
              Shared by <%= link_to post.user.name, user_path(post.user), class: "name" %>
            </p>
            <span class="buttons">
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_likes.size %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="form_heading">New Vision</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show">

  <!-- Prev & Next Buttons -->
  <p class="js-next" data-id="<%= @post.id %>">
    <%= link_to "Prev", post_path(@post.prev), class: "next-prev" %> |
    <%= link_to "Next", post_path(@post.next), class: "next-prev" %>
  </p>

  <!-- Post Info -->
  <h1><%= @post.title %></h1>
  <p class="username">
    Shared by <%= link_to @post.user.name, user_path(@post.user), class: "name" %> <%= posted_at %> ago
  </p>

  <!-- Post Image -->
  <div class="clearfix">
    <div class="post_image_description">
      <%= image_tag @post.image.url(:medium) %>

      <!-- Post Description -->
      <div id="body-<%= @post.id %>" class="description">
        <%= truncate(@post.description, length: 150) %><br>
        <button class="primary-btn" id="js-more" data-id="<%= @post.id %>" type="button" name="button">Read More...</button>
      </div>

    </div>

    <!-- Post Controls -->
    <div class="post_data">
      <%= link_to "Vist Link", @post.link, class: "button" %>
      <%= link_to like_post_path(@post), method: :get, class: "data" do %>
         <i class="fa fa-thumbs-o-up"></i>
         <%= pluralize(@post.get_upvotes.size, "Like") %>
      <% end %>
      <%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
         <i class="fa fa-thumbs-o-down"></i>
         <%= pluralize(@post.get_downvotes.size, "Dislike") %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@post.comments.count, "Comment") %>
      </p>
      <%= edit_post %>
      <%= delete_post %>
    </div>
  </div>
</div>

<!-- Comment Section -->
<div id="comments">
  <h3 class="comment_count">Comments</h3>
    <div class="post-comments">
      <% if @post.comments.any? %>
        <% @comments.each do |comment| %>
        <li id="comment"><blockquote><strong><%= comment.user.username %></strong> says:
          <em><%= comment.content %></em></blockquote></li>
        <% end %>
          <div id="new-comment">
            <!-- New Comments created by AJAX call -->
          </div>
      <% else %>
      <div class="no-comments">
            There are no comments for this Vision
          </div>
      <% end %>
    </div>
    <% if signed_in? %>
      <%= render 'comments/form', post: @post, comment: @comment %>
    <% end %>
</div>

app/views/search/index.html.erb
<div class="container">
  <div id="posts">
    <span id="pagination">
    </span>
    <% @posts.each do |post| %>
      <div class="post">
        <div class="post_image">
          <%= link_to (image_tag post.image.url(:small)), user_post_path(post.user, post) %>
        </div>
        <div class="post_content">
          <h2 class="title"><%= link_to post.title, user_post_path(post.user, post) %></h2>
          <div class="data clearfix">
            <p class="username">
              Shared by <%= link_to post.user.name, user_path(post.user), class: "name" %>
            </p>
            <span class="buttons">
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_likes.size %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group row">
    <div class="col-sm-3 col-form-label">
      <%= profile_pic%>
    </div>
    <div class="col-sm-9">
      <p class="username"><%=current_user.name %></p>
      <span><%= link_to "Delete account", edit_user_registration_path(current_user) %></span>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.file_field :avatar, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if user.avatar.exists? %>
  <%= image_tag user.avatar.url, class: "avatar" %>
<% else %>
  <%= image_tag "avatar_png_71508", class: "avatar" %>
<% end %>

<%= link_to user.username, user %>

<% if current_user.admin? && current_user %>
  <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- Profile info section -->
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <%= profile_pic %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <%= edit_profile %>
      </div>
      <ul class="posts">
        <li><span><%= pluralize(@posts.count, "vision") %></span></li>
      </ul>
      <h2 class="name"><%= @user.name %></h2>
      <% if @user == current_user %>
        <a class="email"><%= @user.email %></a>
      <% end %>
      <div class="bio-box">
        <h2 class="bio">Bio:</h2>
        <p><%= @user.bio %></p>
      </div>
    </div>
  </div>
</div>

<!-- Button to Show Posts using AJAX GET request-->
<div class="user-tabs">
  <button id="js-post" class="primary-btn" data-uid="<%= @user.id %>" data-pid="<%= @post.id %>" type="button" name="button">Show <%= @user.name %>'s Images</button>
</div>

<!-- Container to render images   -->
<div class="user-images">

</div>

<!-- JS for Show Post button -->
<script type="text/javascript" charset="utf8">
  $(function() {
    $("#js-post").on("click", function() {
      const userId = $(this).data("uid");
      $.get("/users/" + userId + ".json", function(data) {
        let post = data.posts.map(p => {
          return `
            <div class="wrapper">
              <h6 style="color:gray;text-align: center;"><u>${p.title}</u></h6>
              <a href="<%= user_post_path(@user.posts, @post) %>">
                <img src="${p.image}"><br>
              </a>
            </div>
          `
        })
        $(".user-images").html(post)
        $(".user-title").html(post)
      })
    })
  })
</script>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1 class="welcome-title">Welcome to Visionz!</h1>

  <h2 class="welcome">
    A "vision board" is a collection of images, pictures, quotes and affiramations of a persons dreams and desires. Visionz is an online community and a source of inspiration and motivation. Whether your looking for inspiration for your next project or you want to showcase what inspires you, unlock the visionz!
  </h2>
  <div class="signup-btn">
    <%= link_to "Sign up now!", new_user_registration_path, class: "button" %>
  </div>
</div>